version: "3.7"
services:
  pulsar:
    image: apachepulsar/pulsar:2.5.0
    command: bin/pulsar standalone
    hostname: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    restart: unless-stopped
    volumes:
      - "./data/:/pulsar/data"
      - "./connectors/:/pulsar/connectors"
      - "../streamer/functions/:/pulsar/functions"
      - "../streamer/schemas/:/pulsar/schemas"
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    ports: 
      - "27017-27019:27017-27019"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
